---
title: "Projects"
---

\begin{center}
Welcome tom my project webpage. You will find here a list of ongoing or past projects I have worked on.
\end{center}


- [Replication package of Monge-Naranjo et al., 2019, in Julia (finished)](https://www.paulogcd.com/Replication_Monge_et_al_2019.jl/dev/) :
 Together with [CHAMBON Lionel](https://lionelchambon.github.io/) and [GUGELMO CAVALHEIRO DIAS Paulo](https://www.paulogcd.com/), we proceeded to an attempt of translation from 
 Stata to Julia of the replication package of Monge-Naranjo, Alexander, Juan M. Sánchez, and Raül Santaeulàlia-Llopis.
  “Natural Resources and Global Misallocation.” American Economic Journal: Macroeconomics 11, no. 2 (2019): 79–126,
   available online here : [https://www.jstor.org/stable/26621311](https://www.jstor.org/stable/26621311).
    This was done for the “[Computational Economics](https://floswald.github.io/NumericalMethods/)” class,
     taught during the Fall 2024 Semester by [Florian Oswald](https://floswald.github.io/) at Sciences Po.
      We obtained the grade of 19/20 for this work.

- [Article Review of The carbon footprint of capital, by Chancel and Rehm in 2024](https://www.paulogcd.com/TPEE_Presentation/) : This is a group presentation done during the fall semester of 2024-2025 for the class “Topics in Public and Environmental Economics” taught by [Stefan Pollinger](https://www.stefanpollinger.com/). We were asked to present in one hour the working paper of Chancel and Rehm about how to account the Carbon Footprint of Capital. The link sends you to a dedicated section on Paulo's website with our slides and a detailed summary of the article (here is the [latest version](https://www.dropbox.com/scl/fi/8jsi7pgno80xlhhjsu3zc/CarbonCapital2023ChancelRehm.pdf?rlkey=nu70bve6k1ofmqz2zpttox9gh&e=1)). And here is the [referee report](COMPERAT.Etienne_referee-report_Chancel-and-Rehm.pdf) that we were asked to write individually. These works combined received the grade of 16/20.

- [Macroeconomics Group Presentation about the Diamond Dybvig model of Bank Runs](macro_pre.pdf) : 
This is a group presentation done in the spring semester of 2024 for the "Macroeconomics 2" class taught by [Jean Barthélemy](https://sites.google.com/site/jeanbarthelemyeconomist/home) (Banque de France) that consisted in a one hour presentation of the paper ["Bank runs, Deposit Insurance, and Liquidity"](https://www.jstor.org/stable/1837095), by Douglas W. Diamond and Philip H. Dybvig (2020). We received the grade of 19/20 for this presentation.

- [Microeconomics Group project about modelling class attendance in a Game Theoretical Framework](Micro_Group_Project.pdf) : 
This is a group project done in the spring semester of 2024 for the "Microeconomics 2" class taught by [Emeric Henry](https://sites.google.com/site/emericmlhenry/home) (Sciences Po Paris) that consisted in elaborating a game using notions seen in class. We choose to do it on strategic interactions between students in a context of class attendance. We received the grade of 17.5/20 for this work.

- [Political Economy Theory Paper: "Who controls the flows? A comparative analysis of Fernand Braudel and David Harvey"](theory-paper_braudel-harvey.pdf) : 
This is a theory paper done in the fall semester of 2022 for the POLECON 101 class (Contemporary Theory of Political Economy) taught by [Steven K. Vogel](https://polisci.berkeley.edu/people/person/steven-vogel) at UC Berkeley, that consisted in connecting a reading from an author studied in lecture to an author from our personal references. This work received the grade of A+.
